# Search

msi_store_search_index:
    pattern:  /search
    defaults: { _controller: MsiStoreBundle:Search:index }

# Product

msi_store_product_list:
    pattern:  /products
    defaults: { _controller: MsiStoreBundle:Product:list }

msi_store_product_show:
    pattern:  /products/{id}
    defaults: { _controller: MsiStoreBundle:Product:show }

# Cart Item

msi_store_cart_item_list:
    pattern:  /cart
    defaults: { _controller: MsiStoreBundle:CartItem:list }

msi_store_cart_item_new:
    pattern:  /cart/new
    defaults: { _controller: MsiStoreBundle:CartItem:new }

msi_store_cart_item_edit:
    pattern:  /cart/{id}/edit
    defaults: { _controller: MsiStoreBundle:CartItem:edit }

msi_store_cart_item_delete:
    pattern:  /cart/{id}/delete
    defaults: { _controller: MsiStoreBundle:CartItem:delete }

# Cart

msi_store_cart_admin_show:
    pattern:  /admin/cart/{id}
    defaults: { _controller: MsiStoreBundle:Admin/Cart:show, _admin: msi_store_cart_admin }
    requirements:
        id: \d+

# Checkout

msi_store_checkout_address:
    pattern:  /checkout/address
    defaults: { _controller: MsiStoreBundle:Checkout:address }

msi_store_checkout_load_addresses:
    pattern:  /checkout/load-addresses
    defaults: { _controller: MsiStoreBundle:Checkout:loadAddresses }

msi_store_checkout_pick_address:
    pattern:  /checkout/pick-address
    defaults: { _controller: MsiStoreBundle:Checkout:pickAddress }

msi_store_checkout_summary:
    pattern:  /checkout/summary
    defaults: { _controller: MsiStoreBundle:Checkout:summary }

msi_store_checkout_process:
    pattern:  /checkout/process
    defaults: { _controller: MsiStoreBundle:Checkout:process }

msi_store_checkout_thankyou:
    pattern:  /checkout/thankyou
    defaults: { _controller: MsiStoreBundle:Checkout:thankyou }
