parameters:
#    msi_store.example.class: Msi\StoreBundle\Example

services:
    msi_store.cart_provider:
        class: Msi\StoreBundle\Cart\CartProvider
        arguments: [ @service_container ]
        scope: request

    msi_store.addition_strategy:
        class: Msi\StoreBundle\Cart\DefaultAdditionStrategy

    # msi_store.cookie_listener:
    #     class: Msi\StoreBundle\EventListener\CookieListener
    #     arguments: [ @msi_store.cart_provider ]
    #     scope: request

    msi_store.login_listener:
        class: Msi\StoreBundle\EventListener\LoginListener
        arguments: [ @msi_store.cart_manager ]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }

    msi_store.twig.extension:
        class: Msi\StoreBundle\Twig\Extension\StoreExtension
        arguments: [ @service_container ]
        tags:
            - { name: twig.extension }
        public: false

    msi_store.product_listener:
        class: Msi\StoreBundle\EventListener\ProductListener
        arguments: [ @service_container ]
        tags:
            - { name: doctrine.event_subscriber }

    msi_store.product_image_listener:
        class: Msi\StoreBundle\EventListener\ProductImageListener
        arguments: [ @service_container ]
        tags:
            - { name: doctrine.event_subscriber }

    msi_store.product_category_listener:
        class: Msi\StoreBundle\EventListener\ProductCategoryListener
        arguments: [ @service_container ]
        tags:
            - { name: doctrine.event_subscriber }

    msi_store.address_listener:
        class: Msi\StoreBundle\EventListener\AddressListener
        arguments: [ @service_container ]
        tags:
            - { name: doctrine.event_subscriber }

    msi_store.cart_listener:
        class: Msi\StoreBundle\EventListener\CartListener
        arguments: [ @service_container ]
        tags:
            - { name: doctrine.event_subscriber }

    msi_store.cart_item_listener:
        class: Msi\StoreBundle\EventListener\CartItemListener
        arguments: [ @service_container ]
        tags:
            - { name: doctrine.event_subscriber }
