parameters:
#    vor_core.example.class: Vor\CoreBundle\Example

services:
#    vor_core.example:
#        class: %vor_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
