parameters:
#    vor_search.example.class: Vor\SearchBundle\Example

services:
#    vor_search.example:
#        class: %vor_search.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
